// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhCls1wV7JTQHSfBcOvLjqdUNMdPmF0R0',
    appId: '1:630110267110:web:ebf2c7a9bb118880a1fd27',
    messagingSenderId: '630110267110',
    projectId: 'minhhien-solutions',
    authDomain: 'minhhien-solutions.firebaseapp.com',
    databaseURL: 'https://minhhien-solutions.firebaseio.com',
    storageBucket: 'minhhien-solutions.appspot.com',
    measurementId: 'G-D955S9B7S8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy-m5AHBLbrM7Si2ZbnN0adUlm3VeZneM',
    appId: '1:630110267110:android:a9666bef78cef22ea1fd27',
    messagingSenderId: '630110267110',
    projectId: 'minhhien-solutions',
    databaseURL: 'https://minhhien-solutions.firebaseio.com',
    storageBucket: 'minhhien-solutions.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqgIB6I0e61D1eJDD7vG54zisOg_rr-hQ',
    appId: '1:630110267110:ios:0050cba375f1784ba1fd27',
    messagingSenderId: '630110267110',
    projectId: 'minhhien-solutions',
    databaseURL: 'https://minhhien-solutions.firebaseio.com',
    storageBucket: 'minhhien-solutions.appspot.com',
    iosClientId: '630110267110-8hs2c1p46i9pb5oov6thfte8hi54bt9h.apps.googleusercontent.com',
    iosBundleId: 'andin.ctvhappyhome.io',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqgIB6I0e61D1eJDD7vG54zisOg_rr-hQ',
    appId: '1:630110267110:ios:953372c2e45456e1a1fd27',
    messagingSenderId: '630110267110',
    projectId: 'minhhien-solutions',
    databaseURL: 'https://minhhien-solutions.firebaseio.com',
    storageBucket: 'minhhien-solutions.appspot.com',
    iosClientId: '630110267110-4gramurro4jflo6o8g2c4rrp15p1nqpq.apps.googleusercontent.com',
    iosBundleId: 'com.example.happyHomeCtv',
  );
}
