List<Map<String, dynamic>> sampleData = [
  {
    'id': 1,
    'name': 'Kawasaki Motors',
    'phone': '92799-5252',
    'chuyen_nganh': 'Nhân viên IT',
    'dia_diem': 'Kaigan, Minato-ku, Tokyo',
    'luong': 10000,
    'gioi_tinh': 'Nam/Nữ',
    'trinh_do': 'N2',
    'bang_cap': 'Đại học',
    'demand': 10,
    'current': 2,
    'image': 'lib/assets/job/kawasaki-logo.png',
    'status': 1,
    'id_trinh_do': 2,
    'id_bang_cap': 1,
    'id_gioi_tinh': 3
  },
  {
    'id': 2,
    'name': 'Honda',
    'phone': '25416-9652',
    'chuyen_nganh': 'Kỹ sư phát triển',
    'dia_diem': 'Minato City, Tokyo',
    'luong': 3377,
    'gioi_tinh': 'Nam',
    'trinh_do': 'N1',
    'bang_cap': 'Đại học',
    'demand': 7,
    'current': 5,
    'image': 'lib/assets/job/honda-logo.png',
    'status': 0,
    'id_trinh_do': 1,
    'id_bang_cap': 1,
    'id_gioi_tinh': 1
  },
  {
    'id': 3,
    'name': 'Yamaha',
    'phone': '85412-9652',
    'chuyen_nganh': 'Kỹ sư lắp ráp',
    'dia_diem': 'Iwata, Shizuoka',
    'luong': 1240,
    'gioi_tinh': 'Nam',
    'trinh_do': 'N3',
    'bang_cap': 'Đại học',
    'demand': 2,
    'current': 2,
    'image': 'lib/assets/job/yamaha-logo.png',
    'status': 2,
    'id_trinh_do': 3,
    'id_bang_cap': 1,
    'id_gioi_tinh': 1
  },
  {
    'id': 4,
    'name': 'Suzuki',
    'phone': '65214-8852',
    'chuyen_nganh': 'Kỹ sư kiểm thử',
    'dia_diem': 'Hamamatsu, Shizuoka',
    'luong': 700,
    'gioi_tinh': 'Nam/Nữ',
    'trinh_do': 'N4',
    'bang_cap': 'Đại học',
    'demand': 25,
    'current': 11,
    'image': 'lib/assets/job/suzuki-logo.png',
    'status': 2,
    'id_trinh_do': 4,
    'id_bang_cap': 1,
    'id_gioi_tinh': 3
  },
  {
    'id': 5,
    'name': 'Mazda',
    'phone': '55214-8525',
    'chuyen_nganh': 'Quản lý lắp ráp',
    'dia_diem': 'Fuchu, Hiroshima',
    'luong': 6000,
    'gioi_tinh': 'Nữ',
    'trinh_do': 'N2',
    'bang_cap': 'Đại học',
    'demand': 2,
    'current': 1,
    'image': 'lib/assets/job/mazda-logo.png',
    'status': 1,
    'id_trinh_do': 2,
    'id_bang_cap': 1,
    'id_gioi_tinh': 2
  },
  {
    'id': 6,
    'name': 'Mitsubishi Motors',
    'phone': '14775-5820',
    'chuyen_nganh': 'Quản lý dự án',
    'dia_diem': 'Chiyoda City, Tokyo',
    'luong': 7500,
    'gioi_tinh': 'Nam/Nữ',
    'trinh_do': 'N1',
    'bang_cap': 'Cao đẳng',
    'demand': 1,
    'current': 0,
    'image': 'lib/assets/job/mitsubishi-logo.png',
    'status': 1,
    'id_trinh_do': 1,
    'id_bang_cap': 2,
    'id_gioi_tinh': 3
  },
  {
    'id': 7,
    'name': 'Daikin',
    'phone': '55241-9968',
    'chuyen_nganh': 'Nhân viên Marketing',
    'dia_diem': 'Osaka, Osaka',
    'luong': 1500,
    'gioi_tinh': 'Nữ',
    'trinh_do': 'N3',
    'bang_cap': 'Đại học',
    'demand': 7,
    'current': 3,
    'image': 'lib/assets/job/daikin-logo.png',
    'status': 1,
    'id_trinh_do': 3,
    'id_bang_cap': 1,
    'id_gioi_tinh': 2
  },
];